title: Warren Hartzler
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Driven and passionate Data Analyst with over five years of experience in accounting and finance.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/warren-hartzler-262811147/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
